# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bill.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
import sqlite3
from PyQt5.QtWidgets import  QApplication , QMainWindow ,QTableWidgetItem ,QMessageBox,QAbstractItemView,QCompleter,QTreeWidgetItem,QLineEdit

from PyQt5.QtGui import QStandardItemModel,QPixmap
from PyQt5.QtCore import QDate 
import sys
from B3d  import MainWindow

import time
from datetime import datetime

class Bill(QMainWindow):
    def __init__(self,*args,**kwargs):
        super(Bill,self).__init__(*args,**kwargs)
        self.setupUi(self)
        self.search_name ()
        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 375)

        """name_search combobox """
        self.name_search_box = QtWidgets.QComboBox(Form)
        self.name_search_box.setGeometry(QtCore.QRect(250, 50, 131, 22))
        self.name_search_box.setEditable(True)
        self.name_search_box.setObjectName("name_search_box")
        self.name_search_box.currentTextChanged.connect(self.show_price)

        """spinbox"""
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(150, 50, 42, 22))
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(0, 110, 351, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(230, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(280, 350, 121, 17))
        self.radioButton.setObjectName("radioButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(0, 330, 151, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(150, 330, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        """"toolbutton """
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(310, 80, 25, 19))
        self.toolButton.setObjectName("toolButton")
        self.toolButton.clicked.connect(self.enter_bill)

        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(350, 80, 47, 13))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 50, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.summ = 0
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "البحث عن طريق الاسم"))
        self.label_2.setText(_translate("Form", "العدد"))
        self.radioButton.setText(_translate("Form", "البحث عن طريق ID"))
        self.label_3.setText(_translate("Form", "مجموع الفاتورة"))
        self.toolButton.setText(_translate("Form", "..."))
        self.label_4.setText(_translate("Form", "الادخال"))
        self.label_5.setText(_translate("Form", "السعر"))
    def set_completer(self) :
        if self.radioButton.isChecked():
            self.radioButton.setChecked(False)
        lst=[]
        
        conn = sqlite3.connect('mytable.db')
        curs =conn.cursor()
        database_data= curs.execute('SELECT id FROM tasks  ')
        for indx, i in enumerate(database_data):
            x=str(i).replace('(','')
            x=x.replace(')','')
            x=x.replace(',','')
            lst.append(x)
        self.completer=QCompleter(lst)
        self.name_search_box.setCompleter(self.completer) 
        conn.close()
    def search_name(self) :

        if not self.radioButton.isChecked ( ) :
           lst=[]
        
           conn = sqlite3.connect('mytable.db')
           curs =conn.cursor()
           database_data= curs.execute('SELECT name FROM tasks  ')
           for indx, i in enumerate(database_data):
               
               x=str(i).replace('(','')
               x=x.replace(')','')
               x=x.replace(',','')
               x=x.replace("'","")
               lst.append(x)
              
           self.completer=QCompleter(lst)
           self.name_search_box.setCompleter(self.completer)
           conn.close() 
        else : 
            self.set_completer()
    def enter_bill (self) :
        global summ 
        
        element=self.name_search_box.currentText()
        number=self.spinBox.value()
        price =int(self.lineEdit_2.text())  * number
        self.summ +=price
        if element != '' and number > 0 and price != '' :
            thebill='#العنصر'+ ' ' +f' {element}'+ '      | ' +'العدد'+ ' ' +f'{number} '+ ' |     ' + 'السعر' + f'{price} '
            self.listWidget.addItem(thebill)
            if self.lineEdit.text() == '' :
                total=str(self.summ) + ' SP'
                self.lineEdit.insert(total)
            else :
                self.lineEdit.clear()
                total=str(self.summ) + ' SP'
                self.lineEdit.insert(total)    

        else :
            pass
        b3d=MainWindow()
        b3d.show_detail(element,number)     
    def show_price(self,value):
        
        self.name_search_box.blockSignals (True)
        if value is not None :
            
            conn=sqlite3.connect('mytable.db')
            curs=conn.cursor()
            instru=f"SELECT sell_price FROM tasks WHERE name = '{value}'"
            try :
                x=curs.execute(instru).fetchone()
            except:
                
                return
            if x is not None :       
                selling_price=str(x).strip(')(,')
                self.lineEdit_2.clear()
                self.lineEdit_2.insert(selling_price)
                
            else :
                pass    
            conn.close()
        if self.name_search_box.signalsBlocked() :
            time.sleep(0.1)    
            self.name_search_box.blockSignals (False)    
if __name__ == '__main__':
    a=QApplication(sys.argv)
    w=Bill()
    w.show()
    a.exec_()                            
