# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gain.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
import sqlite3
from PyQt5.QtWidgets import  QApplication , QMainWindow ,QTableWidgetItem ,QMessageBox,QAbstractItemView,QCompleter,QTreeWidgetItem

from PyQt5.QtGui import QStandardItemModel,QPixmap
from PyQt5.QtCore import QDate 
import sys ,timer

import time
from datetime import datetime


class Form(QMainWindow):
    def __init__(self,*args,**kwargs):
        super(Form,self).__init__(*args,**kwargs)
        self.setupUi(self)
        self.add_to_combobox()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 302)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(310, 130, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.get_gain)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(278, 80, 111, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 231, 131))
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setHorizontalHeaderLabels(['الربح','التاريخ'])
        
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(30, 200, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "اظهار"))
        self.textEdit.setPlaceholderText(_translate("Form", "راس المال"))
    def get_gain (self):
        y=0
        last_row=self.tableWidget.rowCount()        
        date=self.comboBox.currentText()
        conn=sqlite3.connect('mytable.db')
        curs=conn.cursor()
        instruction=f" SELECT gain FROM selling_register WHERE date = {date} " 
        data=curs.execute(instruction)
        for i in data :
            
            x=str(i).replace('(','')
            x=x.replace(')','')
            x=x.replace(",","")
            x=int(x)
            y=y+x
            print(y)
        for  j in range(last_row):
            thecell=self.tableWidget.item(j,0)
            if thecell== None :
                

                self.tableWidget.setItem(j,0,QTableWidgetItem(str(y)+'ل.س'))
                self.tableWidget.setItem(j,1,QTableWidgetItem(date))
                self.tableWidget.setRowCount(last_row+1)
                break    
        curs1=conn.cursor()    
        instruction1="SELECT cost_price, number FROM tasks;"
        data=curs1.execute(instruction1)
        total=0
        for i , j in enumerate(data):
            cost=j[1]
            number=j[0]
            x=str(cost).replace('(','')
            x1=str(number).replace('(','')
            x=x.replace(')','')
            x1=x.replace(')','')
            x=x.replace(",","")
            x1=x.replace(",","")
            x2=int(x) * int(x1)
            total=total+x2
        self.textEdit.setText(str(total)+'ل.س')

            
          


    def add_to_combobox(self):
        lst=[]
        conn = sqlite3.connect('mytable.db')
        curs=conn.cursor()
        instruction= "SELECT date FROM  selling_register;"
        date=curs.execute(instruction)
        for i in date :
          
            x=str(i).replace('(','')
            x=x.replace(')','')
            x=x.replace(",","")
            if x not in lst:
                lst.append(x)
        conn.close()
        self.comboBox.addItems(lst)


        
