# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pass.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets 
import sqlite3
from PyQt5.QtWidgets import  QApplication , QMainWindow ,QTableWidgetItem ,QMessageBox,QAbstractItemView,QCompleter,QTreeWidgetItem,QLineEdit

from PyQt5.QtGui import QStandardItemModel,QPixmap
from PyQt5.QtCore import QDate 
import sys 

import time
from datetime import datetime



class password_1(QMainWindow):
    def __init__(self,*args,**kwargs):
        super(password_1,self).__init__(*args,**kwargs)
        self.setupUi(self)
        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        
    def setupUi(self, password_1):
        password_1.setObjectName("password_1")
        password_1.resize(400, 300)
        self.setWindowIcon(QtGui.QIcon('b3d.png'))
        self.groupBox = QtWidgets.QGroupBox(password_1)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 321, 271))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        font1 = QtGui.QFont()
        font1.setPointSize(8)
        font1.setBold(False)
        font1.setWeight(75)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 50, 161, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setFont(font1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 100, 161, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QLineEdit.Password)
        self.lineEdit_2.setFont(font1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 160, 161, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setEchoMode(QLineEdit.Password)
        self.lineEdit_3.setFont(font1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(220, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(200, 100, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(200, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(170, 230, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.set_password)

        self.retranslateUi(password_1)
        QtCore.QMetaObject.connectSlotsByName(password_1)

    def retranslateUi(self, password_1):
        _translate = QtCore.QCoreApplication.translate
        password_1.setWindowTitle(_translate("password", "PASSWORD"))
        self.groupBox.setTitle(_translate("password", "كلمة المرور"))
        self.label.setText(_translate("password", "الاسم"))
        self.label_2.setText(_translate("password", "كلمة المرور الجديدة"))
        self.label_3.setText(_translate("password", "اعادة كلمة المرور"))
        self.pushButton.setText(_translate("password", "حفظ"))
    def set_password(self):
        if  self.lineEdit_2.text() ==self.lineEdit_3.text() :

           user_name =self.lineEdit.text()
           user_password =self.lineEdit_2.text()   
        else :
            QMessageBox.information(self,"حطأ","كلمة المرور غير متطابقة")
            return
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()      
        self.store_password(user_name,user_password) 
        self.enable()
        self.close()   
    def store_password(self,user_name,user_password):
        conn=sqlite3.connect('goodlife.db')
        curs=conn.cursor()
        instru=f"""INSERT INTO  safe 
               (user_name,user_password)VALUES('{user_name}','{user_password}')
                  """
        curs.execute(instru)
        conn.commit()
        conn.close() 
    def enable (self):
        with open ('var.txt','w') as f:
            f.write('B3d')     
               
def main1():
   w=password()
   w.show()



   
      
      
          